disabled_rules:
  - variable_name
  - force_cast
  - function_body_length
  - variable_name_min_length
included:
  - Yomu
  - YomuTests
excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - Pods
  - R.generated.swift
