before_install:
  - type swiftlint >/dev/null 2>&1 || (brew update && brew install swiftlint) # Install swiftlint if it's not installed
  - curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.18.1/Carthage.pkg"
  - sudo installer -pkg "Carthage.pkg" -target /
  - rm "Carthage.pkg"
  - carthage version # Print version for debugging purposes
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode9.4
      script:
        - travis_retry make bootstrap
        - make test
      env: JOB=CI_BUILD_TEST
    - os: osx
      language: objective-c
      osx_image: xcode9.4
      script:
        - travis_retry make package
      env: JOB=CI_BUILD_PACKAGE
deploy:
  provider: releases
  api_key:
    secure: rv3j7nFh0Pwszmji5jrL9l4RFiWPpSMc8gfyuRosGb0QNFYAI5R/S/TMGS4hD6yxQ4fN3GqJsI0Z32/jhlVODMkuz+9Dgw/8WQK0EQ/sEGKdnt41aGv5nJmSrNrhXZNyD/Iz8nBGRadIpEIbkqK1lnGT0RlK/D1ZFCE5CumJvxr1mNa9L1crwexgh7jWkDoARjfRRhW63M57zR5CzefAaVhYES/U1P8ZtuWN6xe2ApZwE+VZlnh01OznKEb22gAhr4tV1ywm3x6F31xCpw84CHGP5byl6QkMp9fQbl8XL+oe0D55FaPSeU8oVeDqaSD3uvv8EiTE9uI7DbEtrhJg1dV04BOxkWmr19h0UawG/9xPhY2xNr5B7BPt1yLG2XwOgTPhDYI7BhAB4mu19fC+P1U689Mi0UgixtLq5MKB9+TKVGdcotf7EPZWZ7VxDqCo8GhMYNOB4DUvr0BkHBmDWCG93+g6odH54ZCYNIEfCt+S0YimdriRMSWfOgX/6kBQ4jMMEjQjFO8Jm2462gI8BzVKW6ZUHGFjKAd4ND7LgClbNtUqs5mrYIpIdJVR5w8USq6CKazrTacgZ7wUxbG2blhZ6DQ7kDIk8ZVNZgRAdVcx2pNZ9C6cxi4xCYRSXmV8Vz4d82gHzpX/Y+7QG9DW2Q7b9VLN4kxZnYWX4CwVwlY=
  file: Yomu.pkg
  skip_cleanup: true
  on:
    tags: true
    repo: sendyhalim/Yomu
    condition: $JOB = CI_BUILD_PACKAGE
